### ISSUE TITLE
plugin breaks with netbox 3.5.0 release

### ISSUE THREAD

**Issue by acentoz** [k01ek/netbox-devicetype-importer#22]
I have tried to install the module in the new version of netbox and I realized that it is not compatible, could you please help me.

python3 manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/base.py", line 93, in wrapped
    saved_locale = translation.get_language()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 749, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/opt/netbox/netbox/extras/plugins/__init__.py", line 133, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_devicetype_importer requires NetBox maximum version 3.3.99.

**Comment by david-sieg** [comment]
Same problem here with NetBox 3.5.1

`Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 93, in wrapped
    saved_locale = translation.get_language()
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/srv/netbox/releases/netbox-v3.5.1/venv/lib64/python3.8/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/srv/netbox/releases/netbox-v3.5.1/netbox/netbox/settings.py", line 752, in <module>
    plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
  File "/var/srv/netbox/releases/netbox-v3.5.1/netbox/extras/plugins/__init__.py", line 133, in validate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin netbox_devicetype_importer requires NetBox maximum version 3.3.99.`

**Comment by scoobydooxp** [comment]
Any idea why a specific version is being hardcoded? Is that a Netbox requirement?

**Comment by fatman00** [comment]
Does anyone know how to fix this? I have the same issue with 3.7.x
